# Generated by Django 6.0.1 on 2026-01-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('land_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('land_ownership', models.CharField(max_length=50)),
                ('experience', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
